# Powers the "Sponsor" button on this repo. See:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: slowwave
